//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicalManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoctorTbl()
        {
            this.PrescriptionTbls = new HashSet<PrescriptionTbl>();
        }
    
        public int DocId { get; set; }
        public string DocName { get; set; }
        public string DocPhone { get; set; }
        public int DocExp { get; set; }
        public string DocSpec { get; set; }
        public string DocGen { get; set; }
        public string DocAdd { get; set; }
        public System.DateTime DocDob { get; set; }
        public string DocPass { get; set; }
        public string DocEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescriptionTbl> PrescriptionTbls { get; set; }
    }
}
