//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicalManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaboratorianTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LaboratorianTbl()
        {
            this.LabTestTbls = new HashSet<LabTestTbl>();
        }
    
        public int LabId { get; set; }
        public string LabName { get; set; }
        public string LabEmail { get; set; }
        public string LabPass { get; set; }
        public string LabPhone { get; set; }
        public string LabAddress { get; set; }
        public string LabGen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabTestTbl> LabTestTbls { get; set; }
    }
}
