//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicalManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabTestTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LabTestTbl()
        {
            this.PrescriptionTbls = new HashSet<PrescriptionTbl>();
        }
    
        public int TestId { get; set; }
        public string TestName { get; set; }
        public int TestCost { get; set; }
        public int AddBy { get; set; }
    
        public virtual LaboratorianTbl LaboratorianTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescriptionTbl> PrescriptionTbls { get; set; }
    }
}
