//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicalManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class clinicEntities1 : DbContext
    {
        public clinicEntities1()
            : base("name=clinicEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DoctorTbl> DoctorTbls { get; set; }
        public virtual DbSet<LaboratorianTbl> LaboratorianTbls { get; set; }
        public virtual DbSet<LabTestTbl> LabTestTbls { get; set; }
        public virtual DbSet<PatientTbl> PatientTbls { get; set; }
        public virtual DbSet<PrescriptionTbl> PrescriptionTbls { get; set; }
        public virtual DbSet<ReceptionistTbl> ReceptionistTbls { get; set; }
    }
}
