//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicalManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientTbl()
        {
            this.PrescriptionTbls = new HashSet<PrescriptionTbl>();
        }
    
        public int PatId { get; set; }
        public string PatName { get; set; }
        public string PatPhone { get; set; }
        public string PatGen { get; set; }
        public System.DateTime PatDob { get; set; }
        public string PatAdd { get; set; }
        public string PatAllergies { get; set; }
        public int Addby { get; set; }
    
        public virtual ReceptionistTbl ReceptionistTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescriptionTbl> PrescriptionTbls { get; set; }
    }
}
